### ISSUE TITLE
Links to directories from Markdown local files are reported as 404 even when they exist

### ISSUE THREAD

**Issue by DavidAnson** [JustinBeckwith/linkinator#212]
```bash
pi@pi:~/lnb $ node --version
v14.15.3
pi@pi:~/lnb $ npm ls --depth 0
/home/pi/lnb
└── linkinator@2.8.2
pi@pi:~/lnb $ cat issue.md 
[Link to file](test/file.md)
[Link to directory, works fine in GitHub README](test)
[Alternate link to directory, just curious](test/)
pi@pi:~/lnb $ ./node_modules/.bin/linkinator issue.md --markdown
🏊‍♂️ crawling issue.md
[200] http://localhost:5920/issue.md
[200] http://localhost:5920/test/file.md
[404] http://localhost:5920/test/
[404] http://localhost:5920/test



  [200] http://localhost:5920/issue.md
http://localhost:5920/issue.md
  [200] http://localhost:5920/test/file.md
  [404] http://localhost:5920/test/
  [404] http://localhost:5920/test
ERROR: Detected 2 broken links. Scanned 4 links in 0.269 seconds.
pi@pi:~/lnb $ 
```

**Comment by JustinBeckwith** [comment]
So this is a tricky one.  At its core, `linkinator` is scanning HTML running with a static web server.   If this were a local situation that doesn't take the specifics of Github account, it may be the correct behavior.  I'd expect an `index.html` to exist inside the target directory you're linking too.  Perhaps related - we strictly avoid relative links in our READMEs because of the way they tend to get packaged and passed around on different hosts, like npm.im.  

I can't think of an elegant way to handle this, without starting to add very GitHub specific behaviors.

**Comment by DavidAnson** [comment]
This is workaround-able, so not blocking. However, Markdown link destinations are explicitly allowed to be relative (this isn't specific to GitHub):
- https://daringfireball.net/projects/markdown/syntax#link
- https://spec.commonmark.org/0.29/#example-481

I'm using the `--markdown` parameter, so there seems not to be ambiguity about the scenario. But I'm fine if you close this as being out of scope for the tool.

**Comment by JustinBeckwith** [comment]
Hmm.  I think the issue here is less about relative links, and more about external services (GitHub) that render the link.  For example - if you locally have:

```
website/
  docs/
    some-doc-name.md
  README.md
```

And if `/README.md` has:

```md
[docs](docs/)
```

That's perfectly valid markdown, but *without* GitHub, I would expect it to require an `index.html`, or _maybe_ a `README.md`.  This is all making assumptions about the web server that is eventually going to serve the content.  

Taking 10 steps back - could the answer here be to expose a flag that allows directory listing?  I think that would more broadly cover the scenario you're trying to solve, right?

**Comment by DavidAnson** [comment]
Even without a file, I would expect the web server to render the directory listing. But I think your "10 steps back" proposal is great; an option to allow directory listing would perfectly suit my scenario.
