### ISSUE TITLE
Chrome DevTools Links falsely reporting 404 (on GitHub Pages URLs?)

### ISSUE THREAD

**Issue by bnb** [JustinBeckwith/linkinator#24]
Just ran the following command:

```
npx linkinator https://nodejs.org/dist/latest-v10.x/docs/api/all.html
```

This successfully tested the Node.js API docs for 404s and surfaced two real 404s that can be fixed 🎊 

There were also 4 reported 404s that were all to the Chrome DevTools website:

- https://chromedevtools.github.io/devtools-protocol/tot/Profiler
- https://chromedevtools.github.io/devtools-protocol/v8/Debugger
- https://chromedevtools.github.io/devtools-protocol/v8/
- https://chromedevtools.github.io/devtools-protocol/v8/Profiler

These 404s weren't actually 404s, but were reported as such. I'm not sure if this is because they're hosted on GitHub Pages or there's some other factor at play here. Just wanted to report this so you were aware 💖

**Comment by JustinBeckwith** [comment]
Oh boy, an adventure! 
![image](https://user-images.githubusercontent.com/534619/52732309-ba4f9400-2f74-11e9-81d3-90513efd5de8.png)

It's returning a 404 because... well fetch is returning a 404... even though the page obviously loads.  I am going to start poking around at user agent headers and such to see if it's being a butt.

**Comment by josepharhar** [comment]
It looks like the [gh-pages branch of devtools-protocol](https://github.com/ChromeDevTools/devtools-protocol/tree/gh-pages) makes [that 404 response](https://github.com/ChromeDevTools/devtools-protocol/blob/23e001245d8801fd72be6169a862f44684346a7f/404.html) which redirects you to a valid page by running javascript, which explains why making a request to /devtools-protocol/tot/Profiler without running the javascript to redirect it 404s. @paulirish it would seem that you set it up since you're the only one with commit history on that branch, and I couldn't find how the gh-pages branch gets generated. I don't have any ideas for an alternative to the javascript redirect, do you think this is something we should fix?

**Comment by JustinBeckwith** [comment]
Ah, rats.  I've been there myself - with no control over the backend, your only real option is a client side redirect.  One of the meh parts of GitHub pages.  @bnb - sadly I don't think there's anything I or Paul could do about this one. I would suggest running this with `--skip chromedevtools.github.io` to just leave those out of the query.  

Since there's nothing really actionable - I'm going to close this out for now. If you think of something else we could do here - let me know!  I'm all 👂👂
