### ISSUE TITLE
How to run linkinator for "PUG" files

### ISSUE THREAD

**Issue by CBoensel** [JustinBeckwith/linkinator#535]
I'd like to run linkinator as a lint step for a Node express app that uses "pug" as a templating engine. 

See https://pugjs.org/api/getting-started.html. 

Syntax examples of an `<a>`-tags would be... 

- `a(href=link)`
- `a(href='#{link}')`
- `a.my-css-class(href=link)`

I noticed markdown is supported. Any change, pug could be supported too?

**Comment by CBoensel** [comment]
@JustinBeckwith Help or any insights would still be appreciated if you can bare a minute, please.

**Comment by JustinBeckwith** [comment]
👋  ultimately linkinator works by scanning and parsing HTML files.  Even for the markdown support, it first has to do a compilation step where it's converted to HTML and served from a web server first.  Chances are - you'd be better off actually running your site with node, and then pointing linkinator to the local url instead of trying to statically scan from the file system.  All `linkinator ./path` does anyway is use a tiny homebrew webserver to host the files :)

**Comment by CBoensel** [comment]
Thanks, had a look to the code base. Will evaluate if it's worth the effort. Appreciate your response.
